Collector:
  subreddit: 'explainlikeimfive'
  time_filters: ['all', 'year', 'month', 'week', 'day']
Pairs:
  subreddit: 'explainlikeimfive'
  top_comments: false
Tokenizer:
  vocab_size: 10_000
  max_seq_length: 128
Model:
  lstm:
    embedding_dim: 100
    hidden_dim: 8
    n_layers: 2
    dropout: 0.5
  transformer:
    seq_length: 128
Training:
  epochs: 20
  batch_size: 256